# pylint: disable=line-too-long
"""
Problem 29: Distinct Powers

Problem description:
Consider all integer combinations of a^b for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5.  
How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

Answer: 9183
"""

from utils import profiler


@profiler
def compute() -> int:
    """
    Computes the number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100.
    
    The function generates all integer values for a^b, where a and b range from 2 to 100, 
    and then determines how many unique values exist in the resulting sequence.
    
    The results are stored in a set to automatically handle duplicates, and the length of 
    the set provides the number of distinct terms.

    Returns:
        int: The number of distinct terms in the sequence.
    """
    terms = {a**b for a in range(2, 101) for b in range(2, 101)}
    return len(terms)


if __name__ == "__main__":
    print(f"Problem 29: {compute()}")
